defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  projects:
    output: true
  coa-pages:
    output: true
    order:
      - coa.md
      - coa-pronunciation-guide.md
markdown: kramdown